name: flutter_translate
description: Flutter Translate is a fully featured localization / internationalization (i18n) library for Flutter.
version: 4.0.4
homepage: https://jesway.com
repository: https://github.com/Jesway/Flutter-Translate

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.1

flutter:
